name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GH_HOSTNAME: ${{ vars.GH_HOSTNAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
          
      - name: Download artifact
        run: |
          gh release download v6.0.0 -p "my-java-app.zip" --repo cbhavya09/JAVA-APPLICATION
          
      - name: Deploy to Local Server
        run: |
          # Set up your local server environment
          # Copy the artifact to the server deployment directory
          Expand-Archive -Path "my-java-app.zip" "c:\my-server-directory" -Force
          
          # Navigate to the destination directory
          cd "c:\my-server-directory"
          # Start the server
          java -jar server.jar
