name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      GH_HOSTNAME: ${{ vars.GH_HOSTNAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download artifact
        run: |
          gh release download v6.0.0 -p "my-java-app.zip" --repo cbhavya09/JAVA-APPLICATION
          Expand-Archive -Path "my-java-app.zip" -DestinationPath "my-java-app" -Force

      - name: Deploy to IIS
        run: |
          # Use a command to copy the extracted artifact to your IIS server
          # Example: Use scp or other appropriate tools to copy the files
          pscp -r my-java-app/* user@BG4NBL1091:C:\Users\c.bhavya\Downloads

          
          # Use a command to start the Java application on the IIS server
          plink user@hostname "cd C:\Users\c.bhavya\Downloads && java -jar my-java-app.jar"


     
