name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-java-app
          path: target/my-java-app.jar

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-java-app
          path: ./  # Place the artifact in the root directory of the workspace

      - name: Unzip Artifact
        run: |
          mkdir my-java-app
          tar -xvf my-java-app.zip -C my-java-app

      - name: Deploy to Loacal Server
        run: |
          cd my-java-app
          java -jar my-java-app.jar
