name: Deploy to Local Server

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    env:
      GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download artifact
        run: |
          gh release download v6.0.0 -p "my-java-app.zip" --repo cbhavya09/JAVA-APPLICATION
          Expand-Archive -Path "my-java-app.zip" -DestinationPath "my-java-app" -Force

      - name: Deploy to Local Server
        run: |
          # Copy the extracted artifact to the local server using SSH
          scp -i "C:\Users\c.bhavya\.ssh\id_rsa2.ppk" -r my-java-app/* user@localhost:'C:\Users\c.bhavya\Desktop\deploy'
          
          # Run the Java application on the local server using SSH
          ssh -i "C:\Users\c.bhavya\.ssh\id_rsa2.ppk" user@localhost "cd 'C:\Users\c.bhavya\Desktop\deploy' && java -jar my-java-app.jar"
