name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-java-app
          path: target/my-sample-project.jar

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-java-app
          path: target/my-sample-project.jar  # Adjust the filename and path if needed

      - name: Deploy to Local Server
        run: |
          java -jar target/my-sample-project.jar  # Adjust the filename if needed
