name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-java-app  # Adjust to match the artifact name from the "CI" workflow
          path: target/my-sample-project.jar  # Adjust to match the path where the artifact is downloaded in the workspace

      - name: Create Directory for Artifact
        run: mkdir my-java-app

      - name: Extract ZIP Archive
        run: Expand-Archive -Path "target/my-sample-project.jar" -DestinationPath my-java-app

      - name: Deploy to Local Server
        run: |
          cd my-java-app
          java -jar my-sample-project.jar  # Adjust to match the artifact filename


      

     
