name: CD

on:
  push:
    tags:
      - '*'

  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-release-asset@v1
        with:
          name: Application Artifact

      - name: Deploy to Local Server
        run: |
          # Set up your local server environment
          # Example: Install and configure Apache Tomcat
          # Copy the artifact to the server deployment directory
          Expand-Archive -Path "my-java-app.zip" "D:\actions-runner\_work\JAVA-APPLICATION\JAVA-APPLICATION" -Force
          # Navigate to the destination directory
          cd "D:\actions-runner\_work\JAVA-APPLICATION\JAVA-APPLICATION"
          # Extract the artifact
          unzip my-java-app.zip
          # Start the server
          java -jar server.jar
          # Restart the server or trigger a reload
          # Add the appropriate command here to restart the server or trigger a reload
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Required to create releases
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-java-app
          path: my-java-app.zip
