name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        run: |
          echo "JAVA_HOME=C:\Program Files\Java\jdk-11" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
    
      - name: Build with Maven
        run: C:/apache-maven-3.9.0/bin/mvn clean install

      - name: Package the artifact
        run: |
          $outputPath = "my-java-app.zip"
          $sourcePath = "C:\Users\c.bhavya\Desktop\HDFC PROJ\java-trainning\Bhavya-Java\server\target\server.jar"
          Compress-Archive -Path $sourcePath -DestinationPath $outputPath
          
      - name: Install gh CLI
        run: |
          # Install gh CLI
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt update
          apt install gh
        if: runner.os == 'Linux'
          
      - name: Publish the artifact to GitHub Release
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create v1.1.1 my-java-app.zip --title "Release v1.1.1" --notes "Release notes here"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
